// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW_Nd0iycV-u4rTRozP59HuyikymHKeas',
    appId: '1:839745521219:web:13957d08abd8f9c75af6f6',
    messagingSenderId: '839745521219',
    projectId: 'triptalk-645fd',
    authDomain: 'triptalk-645fd.firebaseapp.com',
    storageBucket: 'triptalk-645fd.appspot.com',
    measurementId: 'G-RRX4H22MSG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3YQbs4Zb3451_re2FMMjMb8ZBhoDJ-zw',
    appId: '1:839745521219:android:1bcb9c4a009e3d555af6f6',
    messagingSenderId: '839745521219',
    projectId: 'triptalk-645fd',
    storageBucket: 'triptalk-645fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGr7RtVvf8FHbNh0zoEE14w5OdYFgDdfw',
    appId: '1:839745521219:ios:e76c1a27a5690f065af6f6',
    messagingSenderId: '839745521219',
    projectId: 'triptalk-645fd',
    storageBucket: 'triptalk-645fd.appspot.com',
    iosBundleId: 'com.example.riptalkAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGr7RtVvf8FHbNh0zoEE14w5OdYFgDdfw',
    appId: '1:839745521219:ios:e76c1a27a5690f065af6f6',
    messagingSenderId: '839745521219',
    projectId: 'triptalk-645fd',
    storageBucket: 'triptalk-645fd.appspot.com',
    iosBundleId: 'com.example.riptalkAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBW_Nd0iycV-u4rTRozP59HuyikymHKeas',
    appId: '1:839745521219:web:dcfd49398ef3eb075af6f6',
    messagingSenderId: '839745521219',
    projectId: 'triptalk-645fd',
    authDomain: 'triptalk-645fd.firebaseapp.com',
    storageBucket: 'triptalk-645fd.appspot.com',
    measurementId: 'G-N6JWKJBQ0N',
  );
}
